import 'package:flutter/material.dart';
import 'package:my_garden/widgets/quiz_card.dart';

List<Widget> quizList = [
  QuizCard(quizNumber: 1),
  QuizCard(quizNumber: 2),
  QuizCard(quizNumber: 3),
  QuizCard(quizNumber: 4),
  QuizCard(quizNumber: 5),
  QuizCard(quizNumber: 6),
  QuizCard(quizNumber: 7),
  QuizCard(quizNumber: 8),
  QuizCard(quizNumber: 9),
  QuizCard(quizNumber: 10),
  QuizCard(quizNumber: 11),
  QuizCard(quizNumber: 12),
  QuizCard(quizNumber: 13),
  QuizCard(quizNumber: 14),
  QuizCard(quizNumber: 15),
  QuizCard(quizNumber: 16),
  QuizCard(quizNumber: 17),
  QuizCard(quizNumber: 18),
  QuizCard(quizNumber: 19),
  QuizCard(quizNumber: 20),
  QuizCard(quizNumber: 21),
  QuizCard(quizNumber: 22),
  QuizCard(quizNumber: 23),
  QuizCard(quizNumber: 24),
  QuizCard(quizNumber: 25),
  QuizCard(quizNumber: 26),
  QuizCard(quizNumber: 27),
  QuizCard(quizNumber: 28),
  QuizCard(quizNumber: 29),
  QuizCard(quizNumber: 30),
  QuizCard(quizNumber: 31),
  QuizCard(quizNumber: 32),
  QuizCard(quizNumber: 33),
];
